steps:
  - name: ':docker: :package:'
    plugins:
      'docker-compose#v1.5.2':
        build: probot-app-license
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - name: ':eslint:'
    command: npm run lint
    plugins:
      'docker-compose#v1.5.2':
        run: probot-app-license
    agents:
      queue: workers
  # - name: ':jest:'
  #   command: npm run jest
  #   plugins:
  #     'docker-compose#v1.5.2':
  #       run: probot-app-license
  #   agents:
  #     queue: workers
